[tls]

[tls.stores]

[tls.stores.default]

[tls.stores.default.defaultCertificate]
certFile = "/etc/traefik/dynamic/selfsigned.crt"
keyFile = "/etc/traefik/dynamic/selfsigned.key"

[[tls.certificates]]
certFile = "/etc/traefik/dynamic/selfsigned.crt"
keyFile = "/etc/traefik/dynamic/selfsigned.key"
stores = ["default"]
