receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: normal
  otlphttp:
    endpoint: http://traefik-otel-collector:3100/otlp
    tls:
      insecure: true
  otlp/tempo:
    endpoint: http://traefik-otel-collector:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - debug
        - otlp/tempo
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      #      processors: [batch]
      exporters: [debug, otlphttp]
