# config.yml

# Enable/disable certain components/features
disabled: false

# Specify the service name
service_name: "jaeger-agent"

# Logging configuration
logging:
  level: "info"

# Define the agent's configuration
agent:
  # Define the host and port for the agent to bind to
  host_port: "0.0.0.0:6831"

# Define the collector's configuration
collector:
  # Define the endpoint where spans should be sent
  # Change this to the appropriate endpoint where spans should be received
  endpoint: "http://jaeger-collector:14268/api/traces"
  # Enable/disable CORS (Cross-Origin Resource Sharing) support
  cors_allowed_origins: ["*"]

# Define the reporter's configuration
reporter:
  # Buffer configuration for spans
  buffer:
    max_spans: 100
    flush_interval: 1s

# Define the sampler's configuration
sampler:
  # Type of sampler to use (e.g., const, probabilistic, rate limitting, remote)
  type: "const"
  # Specify the sampling parameter (e.g., for const sampler, 1 means sample all traces)
  param: 1
