[api]
dashboard = true

[serversTransport]
insecureSkipVerify = true

[entryPoints]
[entryPoints.web]
address = ":80"

[entryPoints.websecure]
address = ":443"

[entryPoints.dashboard]
address = ":8998"

[entryPoints.metrics]
address = ":8999"

[providers]

[providers.docker]
watch = true
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[providers.file]
directory = "/etc/traefik/dynamic"
filename = "/ssl.toml"

[metrics]

[metrics.prometheus]
buckets=[0.1,0.3,1.2,5.0]
addEntryPointsLabels=true
addRoutersLabels=true
addServicesLabels=true
entryPoint="web"

[metrics.prometheus.headerLabels]
useragent = "User-Agent"

[tracing]
[tracing.otlp.grpc]

[log]
level = "DEBUG"
#filePath = "/var/log/traefik/traefik.log"

[accessLog]
filePath = "/var/log/traefik/access.log"
#format = "json"
bufferingSize = 300
addInternals = true

[accessLog.fields]
defaultMode = "keep"

[accessLog.fields.names]
clientUsername = "drop"

[accessLog.fields.headers]
defaultMode = "keep"

[accessLog.fields.headers.names]
"Authorization" = "drop"
"Content-Type" = "keep"
"Content-Length" = "keep"
"Accept-Encoding" = "keep"
"Accept-Language" = "keep"
"User-Agent" = "keep"
"Referer" = "keep"
"X-Forwarded-For" = "keep"
"X-Real-Ip" = "keep"
"X-Forwarded-Proto" = "keep"
"X-Forwarded-Host" = "keep"
"X-Forwarded-Port" = "keep"
"X-Forwarded-Server" = "keep"
"X-Forwarded-Uri" = "keep"
"X-Forwarded-Method" = "keep"
"X-Forwarded-Access-Token" = "keep"
"X-Forwarded-Client-Cert" = "keep"
"X-Forwarded-Client-Cert-Info" = "keep"
"X-Forwarded-Client-Cert-Subject" = "keep"
"X-Forwarded-Client-Cert-Issuer" = "keep"
"X-Forwarded-Client-Cert-Not-After" = "keep"
"X-Forwarded-Client-Cert-Not-Before" = "keep"
"X-Forwarded-Client-Cert-Serial" = "keep"

[accessLog.filters]
#statusCodes = ["200", "300-302"]
retryAttempts = true
#minDuration = "10ms"

#[certificatesResolvers.myresolver.acme]
#    email = "ryan@webgrip.nl"
#    storage = "/letsencrypt/acme.json"
#    [certificatesResolvers.myresolver.acme.httpChallenge]
#        entryPoint = "web"
