[tls]
[tls.stores]
[tls.stores.default]
#DefaultCertificate = { certFile = "/etc/traefik/dynamic/selfsigned.pem", keyFile = "/etc/traefik/dynamic/selfsigned.key" }
DefaultCertificate = { certFile = "/etc/traefik/dynamic/cert.pem", keyFile = "/etc/traefik/dynamic/key.pem" }

[[tls.certificates]]
#certFile = "/etc/traefik/dynamic/selfsigned.crt"
#keyFile = "/etc/traefik/dynamic/selfsigned.key"
certFile = "/etc/traefik/dynamic/cert.pem"
keyFile = "/etc/traefik/dynamic/key.pem"
stores = ["default"]
