tls:
  certificates:
  - certFile: "/etc/traefik/dynamic/cert.pem"
    keyFile: "/etc/traefik/dynamic/key.pem"
    stores:
      - default
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/dynamic/cert.pem"
        keyFile: "/etc/traefik/dynamic/key.pem"