api:
  dashboard: true
  debug: true
  insecure: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  dashboard:
    address: ":8998"
  metrics:
    address: ":8999"

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
#    directory: "/var/traefik/dynamic"
    filename: "/etc/traefik/dynamic/ssl.yml"
    watch: true

metrics:
  otlp:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    explicitBoundaries:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    pushInterval: 1s
    grpc:
      endpoint: traefik-otel-collector:4317
      insecure: true
      headers:
        useragent: "User-Agent"

tracing:
  sampleRate: 0.1 # 10%
  serviceName: "traefik"
  addInternals: true
  otlp:
    grpc:
      endpoint: traefik-otel-collector:4317
      insecure: true
#      tls:
#        cert: /etc/traefik/dynamic/traefik.test.yml
#        key: /etc/traefik/dynamic/traefik.test.yml

log:
  level: "INFO"
#  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "json"
  bufferingSize: 300
  addInternals: true
  fields:
    defaultMode: "keep"
    names:
      clientUsername: "drop"
    headers:
      defaultMode: "keep"
      names:
        "Authorization": "drop"
        "Content-Type": "keep"
        "Content-Length": "keep"
        "Accept-Encoding": "keep"
        "Accept-Language": "keep"
        "User-Agent": "keep"
        "Referer": "keep"
        "X-Forwarded-For": "keep"
        "X-Real-Ip": "keep"
        "X-Forwarded-Proto": "keep"
        "X-Forwarded-Host": "keep"
        "X-Forwarded-Port": "keep"
        "X-Forwarded-Server": "keep"
        "X-Forwarded-Uri": "keep"
        "X-Forwarded-Method": "keep"
        "X-Forwarded-Access-Token": "keep"
        "X-Forwarded-Client-Cert": "keep"
        "X-Forwarded-Client-Cert-Info": "keep"
        "X-Forwarded-Client-Cert-Subject": "keep"
        "X-Forwarded-Client-Cert-Issuer": "keep"
        "X-Forwarded-Client-Cert-Not-After": "keep"
        "X-Forwarded-Client-Cert-Not-Before": "keep"
        "X-Forwarded-Client-Cert-Serial": "keep"
  filters:
    statusCodes: [ "200", "300-302" ]
    retryAttempts: true
    minDuration: "10ms"

#certificatesResolvers:
#  myresolver:
#    acme:
#      email: "ryan@webgrip.nl"
#      storage: "/letsencrypt/acme.json"
#      httpChallenge:
#        entryPoint: "web"
